# -*- coding: utf-8 -*-
"""生成梦渡之座行为级自动测试包 gs_yume_autotest（跳夜结算分流验证，免玩家在线）。

结构搭建复用 validate_ritual_pattern.place_commands（与 gs_ritual_test 同源解析），
锚点隔离在 z=44（gs_ritual_test 带 z<=26）；探针链 schedule 驱动：
build L0 → beds/settle(4) → build L1 → settle(3) → build L2 → settle(4) →
装灵力核心 → settle(1) → say [GS-AUTO] YUME-DONE。
触发方式：tick 标签一次性哨兵（Done 后 15s schedule yume_a），不依赖 stdin。
仅测试专用：验证完成后删除本包（run/world/datapacks/gs_yume_autotest），避免常驻 tick。
"""
import io
import json
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import validate_ritual_pattern as v  # noqa: E402

OUT = "run/world/datapacks/gs_yume_autotest"
AX, AY, AZ = 228, 100, 44  # 隔离锚点（x 与 suite 同列但 z 带不重叠）


def build_fn(pattern, level_no):
    return v.place_commands(pattern, level_no, (AX, AY, AZ),
                            lambda _key, _l=level_no: _l, only_additions=False,
                            resolver=v.resolve_block_test)


def main():
    tags = v.load_block_tags()
    pattern = next(p for p in (v.parse_pattern(raw, tags) for raw in v.load_patterns())
                   if p['id'] == 'gensokyou:yumewatari_circle')
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    fdir = os.path.join(OUT, "data", "gs_yume", "function")
    tdir = os.path.join(OUT, "data", "minecraft", "tags", "function")
    os.makedirs(fdir, exist_ok=True)
    os.makedirs(tdir, exist_ok=True)
    io.open(os.path.join(OUT, "pack.mcmeta"), "w", encoding="utf-8",
            newline="\n").write(json.dumps({"pack": {
        "pack_format": 48, "description": "Yumewatari settlement autotest"}},
        indent=2))
    # 触发：load 标签每次开档重置哨兵（scoreboard 持久化跨运行），tick 首个守卫触发 kick
    io.open(os.path.join(tdir, "load.json"), "w", encoding="utf-8",
            newline="\n").write(json.dumps({"values": ["gs_yume:load_reset"]}, indent=2))
    io.open(os.path.join(tdir, "tick.json"), "w", encoding="utf-8",
            newline="\n").write(json.dumps({"values": ["gs_yume:tick"]}, indent=2))
    core = f"{AX} {AY} {AZ}"
    funcs = {
        "load_reset": [
            "scoreboard objectives add gs_yume dummy",
            "scoreboard players set #once gs_yume 0",
        ],
        "tick": [
            "scoreboard objectives add gs_yume dummy",
            "scoreboard players add #once gs_yume 0",
            "execute if score #once gs_yume matches 0 run function gs_yume:kick",
        ],
        "kick": [
            "scoreboard players set #once gs_yume 1",
            "schedule function gs_yume:yume_a 15s",
        ],
        "yume_a": [
            "forceload add 200 24 292 70",
            "say [GS-AUTO] YUME-BEGIN",
            "schedule function gs_yume:yume_a2 5s",
        ],
        "yume_a2": [
            # 幂等重置：清掉上一轮运行的缓存与电池，保证断言值确定
            f"data modify block {core} StoredSpiritPower set value 0L",
            f"data remove block {core} SpiritCoreBattery",
        ] + build_fn(pattern, 0) + ["schedule function gs_yume:yume_b 8s"],
        "yume_b": [
            f"gs_debug yumewatari beds {core}",
            f"gs_debug yumewatari settle {core} 4",
        ] + build_fn(pattern, 1) + ["schedule function gs_yume:yume_c 8s"],
        "yume_c": [
            f"gs_debug yumewatari beds {core}",
            f"gs_debug yumewatari settle {core} 3",
        ] + build_fn(pattern, 2) + ["schedule function gs_yume:yume_d 8s"],
        "yume_d": [
            f"gs_debug yumewatari beds {core}",
            f"gs_debug yumewatari settle {core} 4",
            f"data merge block {core} "
            '{SpiritCoreBattery:{id:"gensokyou:spirit_core_1",count:1b}}',
            f"gs_debug yumewatari settle {core} 1",
            "schedule function gs_yume:yume_e 25s",
        ],
        # 自发注灵观察：直注 160000 进核心后，缓存按 8000/s 继续搬 25s
        # 预期 sp=640000-25×8000=440000（±一个速率窗），bat=160000+200000=360000
        "yume_e": [
            f"gs_debug yumewatari beds {core}",
            "say [GS-AUTO] YUME-DONE",
        ],
    }
    for name, lines in funcs.items():
        io.open(os.path.join(fdir, name + ".mcfunction"), "w", encoding="utf-8",
                newline="\n").write("# generated by tools/gen_yumewatari_autotest.py\n"
                                    + "\n".join(lines) + "\n")
    print("written:", OUT, "->", sorted(funcs))


if __name__ == "__main__":
    main()
