# gensokyo_materials - 幻想乡素材·物品图标（v2 重新设计）
# 说明：11 种「矿产/土产/木材」已方块化，其贴图见 gensokyo_material_blocks.py（block/）。
# 本文件只保留真正的物品形态：金属锭、粗矿、海产、植物、杂项。
# 调色板角色：o 描边 / c 暗部 / a 基色 / b 高光 / 其余点缀见 PAL_item_*。

PAL_item_rough_cinnabar_ore = {
    '.': None, 'o': (17, 18, 24), 'r': (40, 41, 48), 'a': (69, 68, 76),
    'k': (103, 100, 106), 'c': (102, 20, 29), 'm': (188, 42, 42),
    'n': (246, 104, 72),
}
PAL_item_refined_cinnabar = {
    '.': None, 'o': (48, 12, 20), 'c': (101, 24, 31), 'a': (170, 40, 40),
    'b': (221, 75, 58), 'n': (255, 137, 96),
}
PAL_item_spirit_iron = {
    '.': None, 'o': (14, 36, 49), 'c': (31, 85, 107), 'a': (64, 154, 178),
    'b': (132, 221, 233), 'n': (222, 255, 250),
}
PAL_item_star_silver = {
    '.': None, 'o': (35, 41, 56), 'c': (87, 100, 123), 'a': (157, 174, 197),
    'b': (215, 230, 244), 'n': (255, 255, 255),
}
PAL_item_rough_spirit_iron_ore = {
    '.': None, 'o': (14, 25, 31), 'r': (36, 56, 62), 'a': (64, 91, 98),
    'k': (102, 127, 132), 'v': (18, 104, 122), 'm': (37, 174, 193),
    'n': (139, 239, 244),
}
PAL_item_rough_star_silver_ore = {
    '.': None, 'o': (20, 25, 34), 'c': (56, 66, 78), 'a': (101, 114, 128),
    'k': (148, 160, 174), 'v': (202, 218, 232), 'n': (247, 250, 255),
}
PAL_item_sanzu_flask = {
    '.': None, 'o': (36, 32, 44), 'c': (88, 84, 108), 'a': (158, 154, 180),
    'b': (212, 210, 230), 'w': (214, 236, 246), 'r': (176, 48, 68),
}
PAL_item_spirit_fish = {
    '.': None, 'o': (12, 39, 57), 'c': (25, 91, 121), 'a': (55, 158, 183),
    'b': (126, 218, 230), 'e': (4, 15, 27), 'd': (211, 250, 249),
}
PAL_item_mermaid_scale = {
    '.': None, 'o': (30, 67, 91), 'c': (62, 117, 142), 'a': (120, 190, 207),
    'b': (196, 235, 239), 'd': (240, 213, 225), 'e': (177, 164, 228),
}
PAL_item_tide_crystal = {
    '.': None, 'o': (28, 78, 94), 'c': (56, 150, 170), 'a': (112, 214, 230),
    'b': (214, 252, 255), 'd': (255, 255, 255),
}
PAL_item_dragon_scale = {
    '.': None, 'o': (20, 66, 50), 'c': (38, 104, 78), 'a': (70, 158, 120),
    'b': (150, 232, 192), 'd': (196, 255, 225), 'e': (30, 86, 64),
}
PAL_item_spirit_herb = {
    '.': None, 'o': (20, 48, 31), 'c': (36, 86, 52), 'a': (68, 145, 77),
    'b': (123, 199, 113), 'd': (216, 255, 202),
}
PAL_item_gentian = {
    '.': None, 'o': (29, 45, 104), 'c': (53, 85, 159), 'a': (75, 124, 206),
    'b': (127, 180, 235), 'd': (210, 238, 246), 'g': (32, 85, 53),
    'G': (83, 145, 78),
}
PAL_item_higanbana = {
    '.': None, 'o': (73, 7, 22), 'c': (145, 18, 37), 'a': (202, 34, 49),
    'b': (246, 87, 92), 'g': (49, 105, 61), 'y': (230, 195, 73),
}
PAL_item_magic_mushroom = {
    '.': None, 'o': (38, 18, 52), 'c': (75, 39, 99), 'a': (119, 66, 157),
    'b': (170, 103, 204), 'd': (232, 203, 247), 'e': (224, 215, 195),
}
PAL_item_spirit_charcoal = {
    '.': None, 'e': (150, 235, 140), 'g': (96, 200, 110), 'a': (32, 36, 32),
    'b': (64, 72, 66), 'c': (18, 22, 18),
}
PAL_item_talisman_paper = {
    '.': None, 'o': (92, 72, 58), 'c': (190, 178, 150), 'a': (232, 222, 194),
    'b': (250, 244, 224), 'i': (196, 52, 52),
}
PAL_item_sukima_fragment = {
    '.': None, 'o': (17, 7, 30), 'c': (49, 19, 75), 'a': (87, 38, 127),
    'b': (137, 70, 185), 'e': (56, 28, 83), 'd': (223, 189, 247),
}

TEXES = {
    "item/rough_cinnabar_ore": [
        "................",
        ".....oooooo.....",
        "...oaaaaaaaao...",
        "..ookkkkaaaaaao.",
        ".oakkkkacccaaao.",
        ".oakkccmmnnaaco.",
        "oakcmmnncaarao..",
        "oakcmmnnarkcao..",
        ".okcmmnnaamcco..",
        ".oacmmnnaamco...",
        "..oacmmnnaao....",
        "...oacmmnno.....",
        "....ooaao.......",
        "................",
        "................",
        "................",
    ],
    "item/refined_cinnabar": [
        "................",
        "................",
        "................",
        "................",
        "......oooo......",
        ".....obbbbo.....",
        "....obbbbbbo....",
        "...onbnaaabno...",
        "...obaaccaabo...",
        "...ocaaaaaaco...",
        "....occcccco....",
        ".....oooooo.....",
        "................",
        "................",
        "................",
        "................",
    ],
    "item/rough_spirit_iron_ore": [
        "................",
        "......oooooo....",
        "...ookkkkkaoo...",
        "..okaaaaaaaako..",
        ".orakvvmnnrkaao.",
        "oavvmnnrakkaao..",
        "oavvmnnarakkoo..",
        "oavmnnaarrkkao..",
        ".okvmnnravmvao..",
        ".oavmmnrvmvao...",
        "..oavmmnravo....",
        "...oavmmnno.....",
        "....ooaao.......",
        "................",
        "................",
        "................",
    ],
    "item/spirit_iron": [
        "................",
        "................",
        "................",
        "................",
        "...oooooooooo...",
        "...obbbbbbbco...",
        "...obbbbbbcco...",
        "...obannaacco...",
        "...obannaacco...",
        "...obaaaaccco...",
        "....occcccco....",
        ".....oooooo.....",
        "................",
        "................",
        "................",
        "................",
    ],
    "item/rough_star_silver_ore": [
        "................",
        "......oooo......",
        "....ookkkkoo....",
        "..okaaaaaaaako..",
        ".ockavnnvkaacco.",
        "ocavvnnkacckao..",
        "ocavvnncakkcao..",
        "ocavnnackvcaao..",
        ".ocavvnnckkcaao.",
        ".ocavnnckcaao...",
        "..ocavnnckco....",
        "...ocavnnco.....",
        "....occoaao.....",
        "................",
        "................",
        "................",
    ],
    "item/star_silver": [
        "................",
        "................",
        "................",
        "................",
        ".........obo....",
        "......obbbaao...",
        "....obbbbaaaco..",
        "...obbaanabcco..",
        ".obaaaanbcco....",
        "..obaaaccco.....",
        "...oabacco......",
        "....occo........",
        "................",
        "................",
        "................",
        "................",
    ],
    "item/sanzu_flask": [
        "................",
        "......oooo......",
        "......oaao......",
        ".....oooooo.....",
        ".....owwwwo.....",
        "....oaaaawwo....",
        "...obaaaaawwo...",
        "...obaaaaawwo...",
        "...obrrrrrwwo...",
        "...obrrrrrwwo...",
        "...ocrrrrrwwo...",
        "...occcccccco...",
        "...oooooooooo...",
        "................",
        "................",
        "................",
    ],
    "item/spirit_fish": [
        "................",
        "................",
        "........oooo....",
        ".......obbao....",
        "..oo....ocbado..",
        ".oco.obaaaaaao..",
        "ocaoobaaaaaaeo..",
        "ocaoobaaaaaaeo..",
        "ocaooccaaaaaco..",
        ".oco.occaaaaao..",
        ".ococ.occaaaaoo.",
        "........occao...",
        ".........oco....",
        "................",
        "................",
        "................",
    ],
    "item/mermaid_scale": [
        "................",
        "................",
        "......oooo......",
        "....obbddeeo....",
        "..obbaaaddaeeo..",
        ".obbaaddaaaacco.",
        ".obbbaaddaaaaco.",
        ".obbaaddaaddaco.",
        "..obaaaaeeccco..",
        "...obaaaaacco...",
        "....obaaacco....",
        ".....obaaco.....",
        ".......co.......",
        "................",
        "................",
        "................",
    ],
    "item/tide_crystal": [
        "................",
        "................",
        ".......oo.......",
        "......obbo......",
        ".....obaaao.....",
        ".....obaaao.....",
        "....obaaaabo....",
        "....obaaaabo....",
        "....obaaadbo....",
        "....ocaaaaco....",
        ".....occcco.....",
        ".....oooooo.....",
        "................",
        "................",
        "................",
        "................",
    ],
    "item/dragon_scale": [
        "................",
        "................",
        "................",
        ".....oooooo.....",
        "...oobbbbbboo...",
        "..obbaadddabbo..",
        ".obbaaaadaaabbo.",
        ".obaaeadadaeabo.",
        ".obaaaeaddaeabo.",
        ".obaaaaadaaabo..",
        "..obaaadaabo....",
        "...obaaaabo.....",
        "....occcco......",
        ".....oooo.......",
        "................",
        "................",
    ],
    "item/spirit_herb": [
        "................",
        "................",
        "................",
        "......d..d......",
        ".....obboobbo...",
        ".......oa.......",
        "....obaoa.......",
        "..obbaaaoaba....",
        "..oba..oa.obc...",
        "..obc..oa.obc...",
        ".obba..oa.obco..",
        ".obc...oa.obc...",
        "...oba.oaobc....",
        "....ob.oaob.....",
        ".......oa.......",
        "......oaa.......",
    ],
    "item/gentian": [
        "................",
        "................",
        ".....oooooo.....",
        "....obbbbbo.....",
        "....obaaddbo....",
        "...obaadadabo...",
        "....oadddaco....",
        ".....oadaco.....",
        "......oao..oooo.",
        "......ggg.obabo.",
        ".....gGg.obddco.",
        "....gGgg.oadaco.",
        "....ggGg..oddo..",
        ".....gg..gg.....",
        "......G..G......",
        ".....gg..gg.....",
    ],
    "item/higanbana": [
        "................",
        "................",
        ".......oo.......",
        ".....o.ocao.....",
        "....oc.bb.oca...",
        "...oca.ac.oca...",
        "....ocao.oca....",
        ".....ocao.oac...",
        "......oao.......",
        ".....g.y...y....",
        ".....gy.y..y....",
        "....gy..y..y....",
        "....gy...y..y...",
        "...gy....y..y...",
        "...gy.....y..y..",
        "..g.............",
    ],
    "item/magic_mushroom": [
        "................",
        "................",
        "................",
        "...oooooo.......",
        "..obbbbbbo......",
        ".obaddaaddabo...",
        ".obaaddaaabbo...",
        "..occcccco.oooo.",
        "....oeeo..obbbo.",
        "....oeeo.obaaabo",
        "....oeeo..occcco",
        "....oeeo...oeeo.",
        ".....oeeo...oeo.",
        ".....oeco...oco.",
        "....oeeco...oeo.",
        ".....oooo....oo.",
    ],
    "item/spirit_charcoal": [
        "................",
        "................",
        "......eeee......",
        ".....ebbbbe.....",
        "....ebbbggge....",
        "...ebbagaaabe...",
        "..ebaaagaagabe..",
        ".ebaaagaaaagaabe",
        ".ebagaaaaaagabe.",
        ".ebaaaaaaaaaabe.",
        ".ecaaagaaaage...",
        "..ecaaagaabe....",
        "...ecccccce.....",
        "....eeeeee......",
        "................",
        "................",
    ],
    "item/talisman_paper": [
        "................",
        ".....oooooo.....",
        ".....obbbbo.....",
        ".....obaaao.....",
        ".....obiaio.....",
        ".....obiiao.....",
        ".....obiaio.....",
        ".....obaaao.....",
        ".....obiiio.....",
        ".....obaaao.....",
        ".....obccco.....",
        ".....occcco.....",
        ".....oooooo.....",
        "................",
        "................",
        "................",
    ],
    "item/sukima_fragment": [
        "................",
        ".......oo.......",
        ".....obbbbo.....",
        "....oobaaaabo...",
        "..oobaddaaboo...",
        ".oobae..aabco...",
        "oobae..aabco....",
        "oobae..aabco....",
        ".obae.edd.aabco.",
        ".obaaee...abco..",
        "..obbaaaabco....",
        "...obbbaco......",
        ".....occo.......",
        "......ooo.......",
        "................",
        "................",
    ],
}
